name: MAUI Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/XkcdViewer.Maui/**/*'
      - '.github/workflows/main.yml' 

defaults:
  run:
    shell: pwsh

env:
  XCODE_VERSION: '26.4'
  DOTNET_VERSION: "10.0.x"
  NET_TFM: 'net10.0'
  PROJECT_PATH: "src/XkcdViewer.Maui/XkcdViewer.Maui.csproj"
  NUGETCONFIG_PATH: "src/nuget.config"
  BUILD_CONFIG: Debug
  TELERIK_USERNAME: "api-key"
  TELERIK_PASSWORD: ${{secrets.TELERIK_NUGET_KEY}}
  TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY_VALUE}}

jobs:
# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
  maui-android:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - uses: actions/setup-java@v5
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Install MAUI workload
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}

    - name: Build Maui Android project
      run: dotnet build ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIG}} -f ${{env.NET_TFM}}-android --no-restore


# ***************************** #
# >>>>>>> Windows Build <<<<<<< #
# ***************************** #
  maui-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    # For WinUI builds
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install MAUI workload
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}

    - name: Build Maui WinUI project
      run: dotnet build ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIG}} -f ${{env.NET_TFM}}-windows10.0.22621.0 --no-restore


# ************************* #
# >>>>>>> iOS Build <<<<<<< #
# ************************* #
  maui-ios:
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{env.XCODE_VERSION}}

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Install MAUI workload
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}

    - name: Build iOS project
      run: dotnet build ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIG}} -f ${{env.NET_TFM}}-ios --no-restore -p:MtouchLink=SdkOnly

# ********************************* #
# >>>>>>> MacCatalyst Build <<<<<<< #
# ********************************* #
  maui-maccatalyst:
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{env.XCODE_VERSION}}

    - name: Install MAUI workload
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}
      
    - name: Build MacCatalyst project
      run: dotnet build ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIG}} -f ${{env.NET_TFM}}-maccatalyst --no-restore -p:MtouchLink=SdkOnly