name: MAUI Release

on:
  # manually executed using main
  workflow_dispatch:
  
jobs:
  checks:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get AAD Secret
      id: aad-secret
      uses: LanceMcCarthy/akeyless-aad-secret@v1
      with:
        akeyless-secret-path: '/DevTools/live-azure-ad'
        akeyless-access-id: 'p-m9vvgiii6rip'
        akeyless-access-key: '${{ secrets.AKEYLESS_ACCESS_KEY }}'
          
    - name: Verify Output
      shell: pwsh
      run: |
        echo "${{ steps.aad-secret.outputs.app-id }}"
        echo "${{ steps.aad-secret.outputs.tenant-id }}"
        echo "${{ steps.aad-secret.outputs.secret-text }}"
        echo "${{ steps.aad-secret.outputs.key-id }}"
        echo "${{ steps.aad-secret.outputs.display-name }}"
          
    - name: Sign files with Trusted Signing
      uses: azure/trusted-signing-action@v0.4.0
      with:
        azure-tenant-id: "${{steps.aad-secret.outputs.tenant-id}}"
        azure-client-id: "${{steps.aad-secret.outputs.app-id }}"
        azure-client-secret: "${{steps.aad-secret.outputs.secret-text}}"
        endpoint: https://eus.codesigning.azure.net/
        trusted-signing-account-name: PrimaryCodeSign
        certificate-profile-name: Codesign-Primary
        files-folder: ${{github.workspace}}/src/XkcdViewer.Maui/Resources/Fonts
        files-folder-filter: ttf
        file-digest: SHA256
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256